from django.conf.urls import patterns, url
from transaction import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns('',
		url(r'^$', views.home, name='home'),
		url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'transaction/login.html'}),
		url(r'^logout/$', views.logout_please, name='logout'),
		url(r'^nasabah/$', views.nasabah, name='nasabah'),
		url(r'^nasabah_kolektif/$', views.nasabah_kolektif, name='nasabah_kolektif'),
		url(r'^nasabah_add/$', views.nasabah_add, name='nasabah_add'),
		url(r'^nasabah_edit/(?P<nasabah_id>\d+)/$', views.nasabah_edit, name='nasabah_edit'),
		url(r'^vendor/$', views.vendor, name='vendor'),
		url(r'^vendor_add/$', views.vendor_add, name='vendor_add'),
		url(r'^vendor_edit/(?P<vendor_id>\d+)/$', views.vendor_edit, name='vendor_edit'),
		url(r'^pembelian/$', views.pembelian, name='pembelian'),
		url(r'^pembelian_add/$', views.pembelian_add, name='pembelian_add'),
		url(r'^penjualan/$', views.penjualan, name='penjualan'),
		url(r'^penjualan_add/$', views.penjualan_add, name='penjualan_add'),
		url(r'^konversi/$', views.konversi, name='konversi'),
		url(r'^konversi_add/$', views.konversi_add, name='konversi_add'),
		url(r'^penarikan/$', views.penarikan, name='penarikan'),
		url(r'^penarikan_add/$', views.penarikan_add, name='penarikan_add'),
		url(r'^kategori/$', views.kategori, name='kategori'),
		url(r'^kategori_edit/(?P<kategori_id>\d+)/$', views.kategori_edit, name='kategori_edit'),
		url(r'^kategori_add/$', views.kategori_add, name='kategori_add'),
		url(r'^nasabah_detail/(?P<nasabah_id>\d+)/$', views.nasabah_detail, name='nasabah_detail'),
		url(r'^vendor_detail/(?P<vendor_id>\d+)/$', views.vendor_detail, name='vendor_detail'),
		url(r'^pembelian_detail/(?P<pembelian_id>\d+)/$', views.pembelian_detail, name='pembelian_detail'),
		url(r'^pembelian_print/(?P<pembelian_id>\d+)/$', views.pembelian_print, name='pembelian_print'),
		url(r'^pembelian_del/(?P<pembelian_id>\d+)/$', views.pembelian_del, name='pembelian_del'),
		url(r'^penjualan_detail/(?P<penjualan_id>\d+)/$', views.penjualan_detail, name='penjualan_detail'),
		url(r'^penjualan_print/(?P<penjualan_id>\d+)/$', views.penjualan_print, name='penjualan_print'),
		url(r'^penjualan_del/(?P<penjualan_id>\d+)/$', views.penjualan_del, name='penjualan_del'),
		url(r'^penarikan_del/(?P<penarikan_id>\d+)/$', views.penarikan_del, name='penarikan_del'),
		url(r'^konversi_detail/(?P<konversi_id>\d+)/$', views.konversi_detail, name='konversi_detail'),
		url(r'^konversi_del/(?P<konversi_id>\d+)/$', views.konversi_del, name='konversi_del'),
		url(r'^stok_detail/(?P<stok_id>\d+)/$', views.stok_detail, name='stok_detail'),
		url(r'^laba_rugi/$', views.laba_rugi, name='laba_rugi'),
		url(r'^arus_barang/$', views.arus_barang, name='arus_barang'),
	)